"""Identity lifting and Gaussian grouping logic."""

from gsegmenter.mapping.gaussian_io import (
    GaussianCloud,
    load_gaussian_cloud,
    load_gaussian_table,
    rgb_to_sh_dc,
    write_gaussian_table,
)
from gsegmenter.mapping.gaussian_noise import (
    GaussianNoiseReport,
    GaussianPruneSpec,
    GaussianQualitySpec,
    build_gaussian_prune_mask,
    build_gaussian_quality_scores,
    compute_gaussian_noise_report,
    compute_isolated_mask,
    filter_gaussian_sidecar,
    infer_voxel_size,
)
from gsegmenter.mapping.lifting import (
    VoteEvidence,
    build_depth_consistency_mask,
    build_frame_vote_evidence,
    collect_mask_hits,
    save_vote_evidence,
    save_vote_summary,
)
from gsegmenter.mapping.association import (
    AssociationPair,
    LABEL_FAMILY_KEYWORDS,
    LocalInstanceEvidence,
    aggregate_local_instances,
    assign_global_objects,
    build_association_pairs,
    infer_label_family,
    load_vote_evidence,
)
from gsegmenter.mapping.grouping import (
    GaussianGroup,
    assign_gaussians_to_global_objects,
    summarize_gaussian_groups,
)
from gsegmenter.mapping.cluster_proposals import (
    GaussianClusterProposal,
    build_voxel_connected_components,
    filter_and_remap_components,
    summarize_cluster_proposals,
)
from gsegmenter.mapping.identity_instances import (
    IdentityInstanceProposal,
    build_identity_instance_ids,
    save_identity_instance_summary,
    write_identity_instance_highlight_ply,
)
from gsegmenter.mapping.category_discovery import (
    CategoryDiscoverySpec,
    CategoryInstanceProposal,
    accumulate_category_votes,
    build_category_instance_ids,
    default_category_specs,
    match_category,
    save_category_instance_summary,
    write_category_instance_highlight_ply,
)
from gsegmenter.mapping.visibility import (
    build_front_depth_buffer,
    filter_front_visible_points,
)
from gsegmenter.mapping.interiorgs_grouping import (
    InteriorGSBox,
    InteriorGSGroup,
    assign_gaussians_to_interiorgs_objects,
    build_interiorgs_boxes,
    compute_points_in_box_mask,
    save_interiorgs_group_outputs,
    summarize_interiorgs_groups,
)
from gsegmenter.mapping.group_diagnostics import (
    GroupVisibilitySummary,
    find_best_frame_for_group,
    select_group_ids,
)
from gsegmenter.mapping.evaluation import (
    GAUSSIAN_COMPARISON_LABELS,
    GaussianGroupingMetrics,
    GroupMatch,
    LabelMetric,
    classify_gaussian_grouping,
    evaluate_gaussian_grouping,
    metrics_to_json_dict,
    summarize_gaussian_comparison,
)

__all__ = [
    "AssociationPair",
    "GAUSSIAN_COMPARISON_LABELS",
    "GaussianCloud",
    "GaussianClusterProposal",
    "CategoryDiscoverySpec",
    "CategoryInstanceProposal",
    "GaussianNoiseReport",
    "GaussianPruneSpec",
    "GaussianQualitySpec",
    "GaussianGroup",
    "GaussianGroupingMetrics",
    "GroupMatch",
    "InteriorGSBox",
    "InteriorGSGroup",
    "IdentityInstanceProposal",
    "GroupVisibilitySummary",
    "LabelMetric",
    "LocalInstanceEvidence",
    "LABEL_FAMILY_KEYWORDS",
    "VoteEvidence",
    "accumulate_category_votes",
    "aggregate_local_instances",
    "assign_gaussians_to_global_objects",
    "assign_gaussians_to_interiorgs_objects",
    "assign_global_objects",
    "build_frame_vote_evidence",
    "build_depth_consistency_mask",
    "build_association_pairs",
    "build_interiorgs_boxes",
    "build_gaussian_prune_mask",
    "build_gaussian_quality_scores",
    "build_category_instance_ids",
    "build_identity_instance_ids",
    "build_voxel_connected_components",
    "build_front_depth_buffer",
    "classify_gaussian_grouping",
    "collect_mask_hits",
    "compute_gaussian_noise_report",
    "compute_points_in_box_mask",
    "compute_isolated_mask",
    "evaluate_gaussian_grouping",
    "find_best_frame_for_group",
    "filter_gaussian_sidecar",
    "filter_and_remap_components",
    "filter_front_visible_points",
    "default_category_specs",
    "infer_voxel_size",
    "infer_label_family",
    "match_category",
    "load_gaussian_cloud",
    "load_gaussian_table",
    "load_vote_evidence",
    "metrics_to_json_dict",
    "rgb_to_sh_dc",
    "save_vote_evidence",
    "save_vote_summary",
    "save_interiorgs_group_outputs",
    "save_identity_instance_summary",
    "save_category_instance_summary",
    "select_group_ids",
    "summarize_gaussian_groups",
    "summarize_cluster_proposals",
    "summarize_gaussian_comparison",
    "summarize_interiorgs_groups",
    "write_gaussian_table",
    "write_category_instance_highlight_ply",
    "write_identity_instance_highlight_ply",
]
