"""PLY readers for exported Gaussian Splatting assets."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re

import numpy as np


_SH_C0 = 0.28209479177387814


_PLY_TYPE_MAP = {
    "char": "i1",
    "uchar": "u1",
    "short": "i2",
    "ushort": "u2",
    "int": "i4",
    "uint": "u4",
    "float": "f4",
    "double": "f8",
}


@dataclass(slots=True)
class GaussianCloud:
    """Named Gaussian property table loaded from an exported PLY file."""

    vertex_count: int
    properties: dict[str, np.ndarray]

    @property
    def xyz(self) -> np.ndarray:
        """Return Gaussian centers as an `(N, 3)` float array."""

        return np.stack(
            [self.properties["x"], self.properties["y"], self.properties["z"]],
            axis=1,
        )

    @property
    def scales(self) -> np.ndarray | None:
        """Return log-scale channels when they are present."""

        scale_keys = ("scale_0", "scale_1", "scale_2")
        if not all(key in self.properties for key in scale_keys):
            return None
        return np.stack([self.properties[key] for key in scale_keys], axis=1)

    @property
    def rotations(self) -> np.ndarray | None:
        """Return quaternion channels in exported storage order."""

        rot_keys = ("rot_0", "rot_1", "rot_2", "rot_3")
        if not all(key in self.properties for key in rot_keys):
            return None
        return np.stack([self.properties[key] for key in rot_keys], axis=1)

    @property
    def opacities(self) -> np.ndarray | None:
        """Return exported opacity logits or values when present."""

        return self.properties.get("opacity")


def _build_vertex_dtype(properties: list[tuple[str, str]]) -> np.dtype:
    """Build a NumPy dtype for the declared vertex property list."""

    return np.dtype([(name, "<" + _PLY_TYPE_MAP[value_type]) for name, value_type in properties])


def _parse_ply_header(handle) -> tuple[int, list[tuple[str, str]], int]:
    """Parse a binary-little-endian PLY header."""

    first_line = handle.readline().decode("ascii").strip()
    if first_line != "ply":
        raise ValueError("Input file is not a PLY stream.")

    fmt_line = handle.readline().decode("ascii").strip()
    if fmt_line != "format binary_little_endian 1.0":
        raise ValueError(f"Unsupported PLY format: {fmt_line}")

    vertex_count: int | None = None
    properties: list[tuple[str, str]] = []
    current_element: str | None = None

    while True:
        line = handle.readline()
        if not line:
            raise ValueError("Unexpected EOF while reading PLY header.")
        decoded = line.decode("ascii").strip()
        if decoded == "end_header":
            break
        if decoded.startswith("comment"):
            continue
        if decoded.startswith("element "):
            match = re.match(r"element\s+(\w+)\s+(\d+)", decoded)
            if match is None:
                raise ValueError(f"Malformed element line: {decoded}")
            current_element = match.group(1)
            if current_element == "vertex":
                vertex_count = int(match.group(2))
            continue
        if decoded.startswith("property "):
            tokens = decoded.split()
            if len(tokens) != 3:
                raise ValueError(
                    "Only scalar vertex properties are supported in Gaussian PLY files."
                )
            if current_element == "vertex":
                _, value_type, name = tokens
                if value_type not in _PLY_TYPE_MAP:
                    raise ValueError(f"Unsupported PLY property type: {value_type}")
                properties.append((name, value_type))
            continue

    if vertex_count is None:
        raise ValueError("PLY file does not declare a vertex element.")

    return vertex_count, properties, handle.tell()


def load_gaussian_table(ply_path: Path) -> tuple[np.ndarray, list[tuple[str, str]]]:
    """Load the raw structured vertex table and header property declarations."""

    ply_path = Path(ply_path)
    with ply_path.open("rb") as handle:
        vertex_count, header_properties, _ = _parse_ply_header(handle)
        dtype = _build_vertex_dtype(header_properties)
        table = np.fromfile(handle, dtype=dtype, count=vertex_count)
    return table, header_properties


def write_gaussian_table(
    ply_path: Path,
    table: np.ndarray,
    header_properties: list[tuple[str, str]],
) -> None:
    """Write a raw structured Gaussian table back to binary-little-endian PLY."""

    ply_path = Path(ply_path)
    ply_path.parent.mkdir(parents=True, exist_ok=True)
    with ply_path.open("wb") as handle:
        header_lines = [
            "ply",
            "format binary_little_endian 1.0",
            "comment Generated by GSegmenter",
            f"element vertex {table.shape[0]}",
        ]
        for name, value_type in header_properties:
            header_lines.append(f"property {value_type} {name}")
        header_lines.extend(["end_header", ""])
        handle.write("\n".join(header_lines).encode("ascii"))
        np.asarray(table, dtype=_build_vertex_dtype(header_properties)).tofile(handle)


def rgb_to_sh_dc(rgb: np.ndarray) -> np.ndarray:
    """Convert RGB colors in `[0, 1]` to first-order SH DC coefficients.

    3DGS stores the base color in `f_dc_*`, where rendering reconstructs color as
    `rgb ~= 0.5 + C0 * f_dc`. This helper applies the inverse transform.
    """

    rgb = np.asarray(rgb, dtype=np.float32)
    return (rgb - 0.5) / _SH_C0


def load_gaussian_cloud(ply_path: Path) -> GaussianCloud:
    """Load exported Gaussian properties from a NerfStudio PLY file."""

    table, header_properties = load_gaussian_table(ply_path)
    properties = {
        name: np.asarray(table[name], dtype=np.float32)
        for name, _ in header_properties
    }
    return GaussianCloud(vertex_count=table.shape[0], properties=properties)
