"""Export a `splat.ply` directly from an identity-aware checkpoint."""

from __future__ import annotations

import argparse
import sys
from collections import OrderedDict
from pathlib import Path
import struct

import numpy as np
import torch

if __package__ is None or __package__ == "":
    sys.path.append(str(Path(__file__).resolve().parents[1]))

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8")

from gsegmenter.training.identity_eval import load_identity_eval_setup
from gsegmenter.training.identity_export import (
    build_identity_export_tensors,
    export_identity_sidecar,
    filter_finite_and_visible_gaussians,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Export splat.ply from an identity-aware config/checkpoint.")
    parser.add_argument("--load-config", type=Path, required=True, help="Path to identity-splatfacto config.yml")
    parser.add_argument("--output-dir", type=Path, required=True, help="Directory where splat.ply will be written")
    parser.add_argument(
        "--ply-color-mode",
        choices=("sh_coeffs", "rgb"),
        default="sh_coeffs",
        help="Whether to export SH coefficients or baked RGB colors.",
    )
    parser.add_argument(
        "--write-identity-sidecar",
        action="store_true",
        help="Write identity_embeddings.npy alongside the exported PLY.",
    )
    parser.add_argument(
        "--output-filename",
        type=str,
        default="splat.ply",
        help="PLY filename inside --output-dir.",
    )
    return parser.parse_args()


def write_binary_ply(path: Path, tensors: OrderedDict[str, np.ndarray]) -> None:
    """Write a binary little-endian PLY matching Nerfstudio's gaussian exporter layout."""

    path.parent.mkdir(parents=True, exist_ok=True)
    count = next(iter(tensors.values())).shape[0]
    header = [
        "ply",
        "format binary_little_endian 1.0",
        "comment Generated by GSegmenter identity exporter",
        f"element vertex {count}",
    ]
    dtypes: list[tuple[str, str]] = []
    for key, value in tensors.items():
        dtype = value.dtype
        if dtype == np.uint8:
            dtypes.append((key, "uchar"))
        else:
            dtypes.append((key, "float"))
    for name, dtype_name in dtypes:
        header.append(f"property {dtype_name} {name}")
    header.extend(["end_header", ""])

    with path.open("wb") as ply_file:
        ply_file.write("\n".join(header).encode("ascii"))
        for i in range(count):
            for key, value in tensors.items():
                row = value[i]
                if np.isscalar(row) or np.asarray(row).ndim == 0:
                    row_values = [row]
                else:
                    row_values = np.asarray(row).reshape(-1)
                for element in row_values:
                    if value.dtype == np.uint8:
                        ply_file.write(struct.pack("<B", int(element)))
                    else:
                        ply_file.write(struct.pack("<f", float(element)))


def main() -> int:
    args = parse_args()
    _, pipeline, checkpoint_path, step = load_identity_eval_setup(args.load_config, test_mode="inference")
    model = pipeline.model

    shs_rest = None
    if hasattr(model, "shs_rest"):
        shs_rest = model.shs_rest.detach().transpose(1, 2).contiguous().cpu().numpy()

    tensors = build_identity_export_tensors(
        positions=model.means.detach().cpu().numpy(),
        opacities=model.opacities.detach().cpu().numpy(),
        scales=model.scales.detach().cpu().numpy(),
        quats=model.quats.detach().cpu().numpy(),
        shs_0=model.shs_0.detach().contiguous().cpu().numpy(),
        shs_rest=shs_rest,
        ply_color_mode=args.ply_color_mode,
    )
    filtered_tensors, invalid_count, low_opacity_count, keep_mask = filter_finite_and_visible_gaussians(tensors)

    output_dir = args.output_dir
    output_path = output_dir / args.output_filename
    write_binary_ply(output_path, filtered_tensors)
    np.save(output_dir / "export_keep_mask.npy", keep_mask)

    identity_sidecar = None
    if args.write_identity_sidecar:
        identity_embeddings = getattr(model, "identity_embeddings", None)
        identity_sidecar = export_identity_sidecar(
            output_dir,
            identity_embeddings=identity_embeddings,
            keep_mask=keep_mask,
        )

    exported_count = next(iter(filtered_tensors.values())).shape[0]
    print(f"Loaded checkpoint: {checkpoint_path} (step {step})")
    print(f"Exported {exported_count} gaussians to {output_path}")
    if invalid_count or low_opacity_count:
        print(f"Filtered invalid={invalid_count}, low_opacity={low_opacity_count}")
    if identity_sidecar is not None:
        print(f"Wrote identity sidecar to {identity_sidecar}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
